# Generated by Django 3.1 on 2020-09-18 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('contatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=50)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoReacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reacao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='perfis.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Reacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('peso', models.IntegerField()),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes', to='perfis.postagem')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacoes_timeline', to='perfis.timeline')),
                ('tipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reacao', to='perfis.tiporeacao')),
            ],
        ),
        migrations.AddField(
            model_name='postagem',
            name='timeline',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='perfis.timeline'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='perfis.usuario'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_perfil', to='perfis.perfil')),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_postagem', to='perfis.postagem')),
            ],
        ),
    ]
